version: "3"

services:
  rabbitmq-container:
    image: rabbitmq:3-management
    ports:
      - 5672:5672
      - 15672:15672
    command: sh -c "rabbitmq-plugins enable rabbitmq_stomp; rabbitmq_web_stomp"
    volumes:
      - ./rabbitmq/definitions.json:/etc/rabbitmq/definitions.json:ro
      - ./rabbitmq/rabbitmq.config:/etc/rabbitmq/rabbitmq.config:ro
  app-container:
    build:
      context: ../../../../
      dockerfile: ./src/main/resources/docker/Dockerfile
    ports:
      - 8080:8080
    environment:
      - SPRING_RABBITMQ_HOST=rabbitmq-container
    depends_on:
      - rabbitmq-container